name: Build Binary

on: [push, pull_request, workflow_dispatch]

jobs:
  build-binary:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Binary
      run: |
        docker build -t plugin_builder .
        docker run --rm -v ${PWD}:/project plugin_builder ./build.sh
    - uses: actions/upload-artifact@v4
      with:
        name: Nintendont loader
        path: "*.dol"
        if-no-files-found: error
